### ISSUE TITLE
New PDF-URL

### ISSUE THREAD

**Issue by do8pgg** [joergschultzelutter/bundesnetzagentur-rufzeichenliste-parser#2]
In Line 46:
Old:
request_url: str = "https://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Telekommunikation/Unternehmen_Institutionen/Frequenzen/Amateurfunk/Rufzeichenliste/Rufzeichenliste_AFU.pdf?__blob=publicationFile"

New:
request_url: str = "https://data.bundesnetzagentur.de/Bundesnetzagentur/SharedDocs/Downloads/DE/Sachgebiete/Telekommunikation/Unternehmen_Institutionen/Frequenzen/Amateurfunk/Rufzeichenliste/rufzeichenliste_afu.pdf",

**Comment by joergschultzelutter** [comment]
Thanks for the heads-up; much appreciated. I've updated the document URL in release 1.04 accordingly.
